steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['test']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcp-cicd-demo', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/gcp-cicd-demo']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run', 'deploy', 'gcp-cicd-demo',
        '--image', 'gcr.io/$PROJECT_ID/gcp-cicd-demo',
        '--region', 'us-central1',
        '--platform=managed',
        '--allow-unauthenticated',
        '--service-account=cloud-build-sa@glassy-totality-463313-r9.iam.gserviceaccount.com'
      ]
images:
  - 'gcr.io/$PROJECT_ID/gcp-cicd-demo'
options:
  logging: CLOUD_LOGGING_ONLY
